/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Product {
  'sku' : string,
  'cost' : number,
  'name' : string,
  'description' : [] | [string],
}
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [string, string, number, [] | [string]],
    undefined
  >,
  'bulkImportProducts' : ActorMethod<[Array<Product>], undefined>,
  'clearAllProducts' : ActorMethod<[], undefined>,
  'containsProduct' : ActorMethod<[string], boolean>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getProductBySKU' : ActorMethod<[string], Product>,
  'getProductCount' : ActorMethod<[], bigint>,
  'listAllProducts' : ActorMethod<[], Array<Product>>,
  'searchProductsByName' : ActorMethod<[string], Array<Product>>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'updateProduct' : ActorMethod<
    [string, string, number, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];