/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'sku' : IDL.Text,
  'cost' : IDL.Float64,
  'name' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'bulkImportProducts' : IDL.Func([IDL.Vec(Product)], [], []),
  'clearAllProducts' : IDL.Func([], [], []),
  'containsProduct' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getProductBySKU' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProductCount' : IDL.Func([], [IDL.Nat], ['query']),
  'listAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'searchProductsByName' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'seedSampleData' : IDL.Func([], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'sku' : IDL.Text,
    'cost' : IDL.Float64,
    'name' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'bulkImportProducts' : IDL.Func([IDL.Vec(Product)], [], []),
    'clearAllProducts' : IDL.Func([], [], []),
    'containsProduct' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getProductBySKU' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProductCount' : IDL.Func([], [IDL.Nat], ['query']),
    'listAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'searchProductsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'seedSampleData' : IDL.Func([], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };